### ISSUE TITLE
noGcInp vs touch

### ISSUE THREAD

**Issue by andrewthad** [byteverse/zlib-bytes#1]
I'm skeptical that `noGcInp` actually works the way it is expected to. Since that value is never accessed, GHC is actually free remove that argument from all of the functions it gets threaded through. There should be a call to `Data.Bytes.touch` somewhere in this library, but there isn't.

**Comment by chessai** [comment]
Agreed. And the function which allocates a `Stream` (which could be a newtype) could just call touch and then NOINLINE
